"""add_migration_jobs_and_invitation_tokens

Revision ID: 06ae94d7aa0e
Revises: 5584d5240ba6
Create Date: 2026-06-25 21:16:00.911396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae94d7aa0e'
down_revision: Union[str, None] = '5584d5240ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('column_mapping', sa.Text(), nullable=True),
    sa.Column('records_total', sa.Integer(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('skipped_details', sa.Text(), nullable=True),
    sa.Column('invitations_sent', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('consent_log', sa.Column('consent_type', sa.String(), nullable=False))
    op.add_column('consent_log', sa.Column('granted', sa.Boolean(), nullable=False))
    op.add_column('consent_log', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('consent_log', 'accepted_at')
    op.drop_column('consent_log', 'document_version')
    op.drop_column('consent_log', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_log', sa.Column('document_type', sa.VARCHAR(), nullable=False))
    op.add_column('consent_log', sa.Column('document_version', sa.VARCHAR(), nullable=False))
    op.add_column('consent_log', sa.Column('accepted_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.drop_column('consent_log', 'created_at')
    op.drop_column('consent_log', 'granted')
    op.drop_column('consent_log', 'consent_type')
    op.drop_table('invitation_tokens')
    op.drop_table('migration_jobs')
    # ### end Alembic commands ###
