"""add_late_cancel_no_show_fees

Revision ID: 5f2647be9373
Revises: 9c30bc2887eb
Create Date: 2026-07-06 21:25:56.645267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2647be9373'
down_revision: Union[str, None] = '9c30bc2887eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_types', sa.Column('late_cancel_fee_override', sa.Float(), nullable=True))
    op.add_column('membership_types', sa.Column('no_show_fee_override', sa.Float(), nullable=True))
    op.add_column(
        'studio_settings',
        sa.Column('late_cancel_fee', sa.Float(), nullable=False, server_default='0.0'),
    )
    op.add_column(
        'studio_settings',
        sa.Column('no_show_fee', sa.Float(), nullable=False, server_default='0.0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studio_settings', 'no_show_fee')
    op.drop_column('studio_settings', 'late_cancel_fee')
    op.drop_column('membership_types', 'no_show_fee_override')
    op.drop_column('membership_types', 'late_cancel_fee_override')
    # ### end Alembic commands ###
